import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useReportStore } from '../../stores/reportStore';
import { DISASTER_TYPES } from '../../lib/types';
import { DISASTER_TYPE_META } from '../../lib/utils';
import { Input, Select } from '../ui';
export default function ReportFiltersBar({ compact }) {
    const filters = useReportStore((s) => s.filters);
    const setFilters = useReportStore((s) => s.setFilters);
    const resetFilters = useReportStore((s) => s.resetFilters);
    return (_jsxs("div", { className: `grid w-full gap-2 ${compact ? 'grid-cols-2 lg:grid-cols-5' : 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-5'}`, children: [_jsx(Input, { placeholder: "Search address, reporter\u2026", value: filters.query, onChange: (e) => setFilters({ query: e.target.value }), className: "col-span-2 lg:col-span-2", "aria-label": "Search reports" }), _jsxs(Select, { value: filters.severity, onChange: (e) => setFilters({ severity: e.target.value }), "aria-label": "Filter by severity", children: [_jsx("option", { value: "all", children: "All severities" }), _jsx("option", { value: "critical", children: "Critical" }), _jsx("option", { value: "high", children: "High" }), _jsx("option", { value: "medium", children: "Medium" }), _jsx("option", { value: "low", children: "Low" })] }), _jsxs(Select, { value: filters.status, onChange: (e) => setFilters({ status: e.target.value }), "aria-label": "Filter by status", children: [_jsx("option", { value: "all", children: "All statuses" }), _jsx("option", { value: "pending", children: "Pending" }), _jsx("option", { value: "investigating", children: "Investigating" }), _jsx("option", { value: "contained", children: "Contained" }), _jsx("option", { value: "resolved", children: "Resolved" }), _jsx("option", { value: "false_alarm", children: "False alarm" })] }), _jsxs("div", { className: "col-span-2 flex gap-2 lg:col-span-1", children: [_jsxs(Select, { value: filters.disasterType, onChange: (e) => setFilters({ disasterType: e.target.value }), "aria-label": "Filter by disaster type", className: "flex-1", children: [_jsx("option", { value: "all", children: "All types" }), DISASTER_TYPES.map((t) => (_jsx("option", { value: t, children: DISASTER_TYPE_META[t].label }, t)))] }), _jsx("button", { type: "button", onClick: resetFilters, className: "min-h-[48px] cursor-pointer touch-manipulation rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-600 hover:bg-slate-50", children: "Reset" })] })] }));
}
